apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.servicePort }} 
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: {{ .Values.targetPort }} 
      nodePort: {{ .Values.feNodePort }} 
