apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}  #mydeployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.appName }}
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: abbas06/backend:latest
        env:
        - name: PORT
          value: {{ .Values.port }}
        - name: REACT_APP_API_URL
          value: {{ .Values.appurl }}  
